language: go
go:
- 1.8.x
install:
- export PATH=${PATH}:${HOME}/gopath/bin
script:
- export PATH=${PATH}:${HOME}/bin
- cd ../../.. && mkdir goa.design && cp -r github.com/goadesign/goa goa.design/goa.v2
- cd goa.design/goa.v2
- make
notifications:
  slack:
    secure: bMYXaoSEGoNdqR0t1VnMAv/4V9PSOhEWyekdJM7p9WmKjJi2yKy0k77uRmwf+5Mrz5GLs3CkZnDha/8cSFld3KEN9SC6QYmIBF/1Pd/5mKHFQOI81i7sTlhrdMv897+6sofEtbBNq1jffhVGVttbMrMWwCTNZu0NrCGBVsDmb44=
